<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Close_testId-pod-image-18673460</name>
   <tag></tag>
   <elementGuidId>8cb71373-9108-4a61-99b6-bd0c80f734d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//img[@id='testId-pod-image-18673460'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.jsx-3107532204.cart-item-image.cart-image-desktop > #testId-pod-image-18673460</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;iPhone 13 128GB&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5058d584-751f-4c58-9522-9392ce53d8fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://media.falabella.com/falabellaPE/18673460/thumbnail</value>
      <webElementGuid>95a60cb7-7ad5-4271-bd76-669e35767ac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>iPhone 13 128GB</value>
      <webElementGuid>8e3e1d6f-61bc-421a-975a-02a910ffa7de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>testId-pod-image-18673460</value>
      <webElementGuid>2639ba58-0db2-42de-a582-7569ed57a242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>52</value>
      <webElementGuid>358b2325-e867-48d6-a7b5-43e22495b3a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>52</value>
      <webElementGuid>53c90ca3-1378-445b-9a01-23ec623610f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jsx-2487856160</value>
      <webElementGuid>529a0b2f-4fa6-4736-abcc-bb1638f277dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;custom_class chakra-ui-light no-scroll&quot;]/div[@class=&quot;jsx-3099744205 jsx-862314242 modal-container   modal-container-desktop&quot;]/div[@class=&quot;doc-click-overlay&quot;]/div[@class=&quot;jsx-3099744205 jsx-862314242 modal false&quot;]/div[@class=&quot;jsx-3099744205 jsx-862314242 modal-body null  false&quot;]/div[@class=&quot;jsx-2711526019 popup small&quot;]/div[@class=&quot;jsx-2711526019 body small with-warning&quot;]/div[@class=&quot;jsx-2711526019 cart-items&quot;]/div[@class=&quot;jsx-3107532204 cart-item-wrapper  mkp&quot;]/div[@class=&quot;jsx-3107532204 cart-item&quot;]/div[@class=&quot;jsx-3107532204 cart-item-image cart-image-desktop&quot;]/img[@id=&quot;testId-pod-image-18673460&quot;]</value>
      <webElementGuid>5893b2c3-005f-4e88-8a78-325aecef8c64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//img[@id='testId-pod-image-18673460'])[2]</value>
      <webElementGuid>e0752b95-ce24-496f-9c87-2df50f315404</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='iPhone 13 128GB']</value>
      <webElementGuid>71535546-59ca-4ac8-9cea-07ee45742090</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/img</value>
      <webElementGuid>566a7466-2ec1-4868-ae26-2780a147befd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://media.falabella.com/falabellaPE/18673460/thumbnail' and @alt = 'iPhone 13 128GB' and @id = 'testId-pod-image-18673460']</value>
      <webElementGuid>1bc9e525-3e74-4519-ba65-46acab0eac6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
