<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__testId-ImageGalleryControlButton-right</name>
   <tag></tag>
   <elementGuidId>5d35c712-e36e-42b9-878c-8d1bfa81c465</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='testId-ImageGalleryControlButton-right']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#testId-ImageGalleryControlButton-right</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#testId-ImageGalleryControlButton-right</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>536d4f20-92b9-4801-a22e-82b050462d8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>testId-ImageGalleryControlButton-right</value>
      <webElementGuid>52f5c3e2-2713-4561-b370-5c51ec1b6f6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4bbf16dc-30ba-4812-9cb3-d8a8c22257bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jsx-438612546 headline-control right</value>
      <webElementGuid>04973aa7-ccf5-4463-b8fc-6f407e10fe8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;testId-ImageGalleryControlButton-right&quot;)</value>
      <webElementGuid>652cfa7b-1d45-490b-8d7b-e526009d53d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='testId-ImageGalleryControlButton-right']</value>
      <webElementGuid>697e0346-2fe9-4e3c-afce-7f8faf31be25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='testId-pod-146172452']/div/div/div[6]/button[2]</value>
      <webElementGuid>60af2a31-1d03-48ec-82d1-ec063fca894f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/button[2]</value>
      <webElementGuid>a53e4b70-ace1-4db4-b0c9-b255df2f2a9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'testId-ImageGalleryControlButton-right' and @type = 'button']</value>
      <webElementGuid>38992e08-7787-4870-9da9-82176bb79d09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
