<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>19cf2e14-cec8-4fd1-bb0d-72721b7afc0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='slider-faceta']/div[2]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;APPLE&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1fdf7ea3-d37b-4f0c-b6ef-e7a936082a76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://media.falabella.com/falabellaPE/20687075_01/w=500,h=500,fit=pad?v1764043128722</value>
      <webElementGuid>bdb59788-fa38-4e5e-8120-5f45916d9915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slider-faceta&quot;)/div[@class=&quot;uxc-huincha-item uxc-huincha-circle-opacity9 uxc-huincha-circle-fondo&quot;]/a[1]/img[1]</value>
      <webElementGuid>ee3f756c-db28-41b2-ba81-257a5f6566be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slider-faceta']/div[2]/a/img</value>
      <webElementGuid>a346f2e1-3fe2-4cd2-bbb1-486b453467ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://media.falabella.com/falabellaPE/20687075_01/w=500,h=500,fit=pad?v1764043128722')]</value>
      <webElementGuid>be32c61c-df8a-413e-927e-a90b95ff3b46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/img</value>
      <webElementGuid>088d1e1c-afeb-4dc6-a49b-f32ee72e691b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://media.falabella.com/falabellaPE/20687075_01/w=500,h=500,fit=pad?v1764043128722']</value>
      <webElementGuid>4d0ed343-8284-4e2f-b9b9-e04cbdd32e03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
