<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Regstrate</name>
   <tag></tag>
   <elementGuidId>404b834e-cc8a-470f-b2f7-4a898fb5ccf6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='unified-login-login-form-register-link']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#unified-login-login-form-register-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Regístrate&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cf5b408f-00b0-4619-b0cb-426d8bda42b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>unified-login-login-form-register-link</value>
      <webElementGuid>b4852c17-2a4e-43b6-a0c0-d34bccac5f7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.falabella.com.pe/falabella-pe/myaccount/registration</value>
      <webElementGuid>2ef41c66-fcda-4c09-87bb-470521b55978</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Regístrate</value>
      <webElementGuid>8a63afb2-c017-4b6b-b39b-70c558ad3e26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;unified-login-login-form-register-link&quot;)</value>
      <webElementGuid>9338edb5-f27d-47d3-a01d-d25909ff4952</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='unified-login-login-form-register-link']</value>
      <webElementGuid>f5dc8269-57f0-4fbd-92d1-59d18d45abe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='testId-cc-login-form']/form/div[4]/p/a</value>
      <webElementGuid>3aac5aec-1a0b-4eb9-8ba0-07b5bbdb9acf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Regístrate')]</value>
      <webElementGuid>7075a603-8e75-41ee-a4bd-0bd2c24031b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ingresar'])[1]/following::a[1]</value>
      <webElementGuid>2469f2a9-8842-4315-a619-bc593d8e2960</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SMS'])[1]/following::a[1]</value>
      <webElementGuid>ff489eda-d74d-40e6-bef1-d6a507ec6533</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.falabella.com.pe/falabella-pe/myaccount/registration')]</value>
      <webElementGuid>a1288a93-4180-4c9a-9f91-723a0817fd59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/p/a</value>
      <webElementGuid>1db99a4d-c6bf-4917-9d76-8f44af1aec58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'unified-login-login-form-register-link' and @href = 'https://www.falabella.com.pe/falabella-pe/myaccount/registration' and (text() = 'Regístrate' or . = 'Regístrate')]</value>
      <webElementGuid>2b2c2f94-113f-4e6a-be07-5ae21938c16b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
