<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Search Bar_UserInfo-module_downArrowico_eb3f45</name>
   <tag></tag>
   <elementGuidId>c4e3d56c-6f60-4027-984d-5759dd58cc97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='user-info']/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.UserInfo-module_downArrowicon__Qs1NR.UserInfo-module_grayDownArrow__NGKaz</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Inicia sesión$/ >> div</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>72b05ff4-79a6-4027-a0e4-cbeb0d9814db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>UserInfo-module_downArrowicon__Qs1NR UserInfo-module_grayDownArrow__NGKaz</value>
      <webElementGuid>68285a8b-dbd9-400d-9022-3c013b301fb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user-info&quot;)/div[@class=&quot;UserInfo-module_info__name__p9TGV&quot;]/div[@class=&quot;UserInfo-module_flex__X0yNy&quot;]/div[@class=&quot;UserInfo-module_downArrowicon__Qs1NR UserInfo-module_grayDownArrow__NGKaz&quot;]</value>
      <webElementGuid>795962a8-1293-4e49-8fcb-e2010c3dbf0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='user-info']/div/div[2]/div</value>
      <webElementGuid>ea52f2c5-d122-4814-978f-3327f46efadb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div</value>
      <webElementGuid>5bb2a8d8-9208-497e-b5f7-42da6bbfcfd1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
