<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__testId-ImageGalleryControlButton-right</name>
   <tag></tag>
   <elementGuidId>902b82c0-94cc-41d6-8d46-e963cc28daec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='testId-ImageGalleryControlButton-right']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#testId-ImageGalleryControlButton-right</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#testId-ImageGalleryControlButton-right</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fbe58581-c28f-4d05-9365-df3d08a48b28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>testId-ImageGalleryControlButton-right</value>
      <webElementGuid>4978494f-a490-4af2-ac66-229ea3b8e077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1503cee0-82c5-4496-af22-c54db6619cd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jsx-438612546 headline-control right</value>
      <webElementGuid>b3f1681b-81a6-428c-9833-df172c9be879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;testId-ImageGalleryControlButton-right&quot;)</value>
      <webElementGuid>2186b6df-b415-4d52-9bc2-e55ef43731ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='testId-ImageGalleryControlButton-right']</value>
      <webElementGuid>55e01157-12a8-44ad-b3b3-570c96e3f28b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='testId-pod-21283554']/div/div/div[6]/button[2]</value>
      <webElementGuid>962ff463-b0cb-4e10-ab2d-30c72220286a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/button[2]</value>
      <webElementGuid>8d05a40e-97d0-4ff0-a0f3-91da4bcce57b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'testId-ImageGalleryControlButton-right' and @type = 'button']</value>
      <webElementGuid>fc8a99a9-11e7-4c03-9c14-5ecf4bf2a0db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
