<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Aceptar_testId-close-cookies-btn</name>
   <tag></tag>
   <elementGuidId>da25d39e-1567-4534-9c16-1fff90fdc702</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='testId-close-cookies-btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#testId-close-cookies-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#testId-close-cookies-btn</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>34e15f74-3176-4d72-a897-75eb7212baff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>testId-close-cookies-btn</value>
      <webElementGuid>0f31ffa1-ee6e-4228-8f16-7f649cf5b46b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Footer-module_close-legal-banner__Tuqyl</value>
      <webElementGuid>d9596279-7375-40a2-bcfd-909ff63fb78f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;testId-close-cookies-btn&quot;)</value>
      <webElementGuid>637ca04c-0396-4f35-a1cf-358cebe1c1f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='testId-close-cookies-btn']</value>
      <webElementGuid>b62526d0-90e6-47f4-9378-9d1fb25438d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/footer/section[4]/div</value>
      <webElementGuid>dc90e31f-2df3-4a85-882d-701adc08c8c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[4]/div</value>
      <webElementGuid>9245b516-2aa9-4cc9-af79-ebea1b0b9324</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'testId-close-cookies-btn']</value>
      <webElementGuid>cf2f30db-8daf-4d0e-b7c9-1fe96984d19b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
