<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Agregar al Carro_testId-pod-image-https_75feb0</name>
   <tag></tag>
   <elementGuidId>dcdaca1a-a3b3-4d4d-a1fe-f19825a7ff66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//img[@id='testId-pod-image-https://media.falabella.com.pe/falabellaPE/136552650_01/public'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;APPLE - IPhone 17 Pro Max Intelligence 256GB (eSIM) - Silver + Combo Regalo APPLE IPhone 17 Pro Max Intelligence 256GB (eSIM) - Silver + Combo Regalo Por Oh Shop S/ 6,199 -11% S/ 6,999 Envío gratis Retira mañana      (3) Agregar al Carro&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>701f8d5b-50f0-4682-bdad-50bc9771f25c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://media.falabella.com.pe/falabellaPE/136552650_01/width=240,height=240,quality=70,format=webp,fit=pad</value>
      <webElementGuid>ee4acda8-2cec-4d9c-8bfb-7a162e24c90b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://media.falabella.com.pe/falabellaPE/136552650_01/width=480,height=480,quality=70,format=webp,fit=pad 2x</value>
      <webElementGuid>0e4925ba-b81b-4578-9cd5-06ce86baf0af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>APPLE - IPhone 17 Pro Max Intelligence 256GB (eSIM) - Silver + Combo Regalo</value>
      <webElementGuid>bed7cd36-7cf1-45b5-8242-9b92e95a5215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>testId-pod-image-https://media.falabella.com.pe/falabellaPE/136552650_01/public</value>
      <webElementGuid>94ce96d0-f7b7-4062-bb04-670c648ad713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>240</value>
      <webElementGuid>5a21718e-07a4-4984-bcd2-d106c4cc104b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>240</value>
      <webElementGuid>8d305130-bad6-43cc-94f9-d638fc03e74d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jsx-1996933093</value>
      <webElementGuid>b7ca252f-9e23-4059-8635-fe938afdaa8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;testId-pod-136552650&quot;)/div[@class=&quot;jsx-4134261027 jsx-3390574944 pod-head&quot;]/div[@class=&quot;jsx-1273315118&quot;]/section[@class=&quot;jsx-1273315118 image--active layout_grid-view layout_view_4_GRID&quot;]/picture[@class=&quot;jsx-1996933093&quot;]/img[@id=&quot;testId-pod-image-https://media.falabella.com.pe/falabellaPE/136552650_01/public&quot;]</value>
      <webElementGuid>4fd09ae1-110f-4a88-9136-cb533857f395</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//img[@id='testId-pod-image-https://media.falabella.com.pe/falabellaPE/136552650_01/public'])[2]</value>
      <webElementGuid>3dc915e8-36ef-42b9-8c02-ee828af643af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='testId-pod-136552650']/div/div/section/picture/img</value>
      <webElementGuid>09162c9d-b5b1-4178-bcd7-76b8d276f700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='APPLE - IPhone 17 Pro Max Intelligence 256GB (eSIM) - Silver + Combo Regalo'])[6]</value>
      <webElementGuid>c9cbdc3f-9cee-45dc-8856-f389073a5bfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/div/div/section/picture/img</value>
      <webElementGuid>b534db7b-1c46-4d31-95fd-314ec03bf2f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://media.falabella.com.pe/falabellaPE/136552650_01/width=240,height=240,quality=70,format=webp,fit=pad' and @alt = 'APPLE - IPhone 17 Pro Max Intelligence 256GB (eSIM) - Silver + Combo Regalo' and @id = 'testId-pod-image-https://media.falabella.com.pe/falabellaPE/136552650_01/public']</value>
      <webElementGuid>583c6f85-fc29-427e-9137-562e39a4f95f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
