<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Agregar al Carro_testId-ImageGallery_4fa8d4</name>
   <tag></tag>
   <elementGuidId>d526ce14-a342-4ca2-b164-4d519ec6ea83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='testId-ImageGalleryControlButton-right']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#testId-ImageGalleryControlButton-right</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#testId-ImageGalleryControlButton-right</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3f6242dd-a93d-4108-9ce5-6c8cb2fc5fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>testId-ImageGalleryControlButton-right</value>
      <webElementGuid>bc8c52d2-5f88-4311-bff9-87d106e73a04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f2f5576d-34dd-4d06-b1f4-6faaf1281c50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jsx-438612546 headline-control right</value>
      <webElementGuid>939fc223-1592-4907-b958-348461e408ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;testId-ImageGalleryControlButton-right&quot;)</value>
      <webElementGuid>6708a0e3-1367-4ef5-83a7-7ff7d8c216a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='testId-ImageGalleryControlButton-right']</value>
      <webElementGuid>b100c113-9ff8-4a91-a8df-5d4faf064faf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='testId-pod-20936200']/div/div/div[6]/button[2]</value>
      <webElementGuid>2b7571b7-7f15-4d7c-9cc6-753bf311e670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/button[2]</value>
      <webElementGuid>8f31f592-7e73-4ead-88f0-ca7efa151891</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'testId-ImageGalleryControlButton-right' and @type = 'button']</value>
      <webElementGuid>3a194ed7-e7fb-43fc-b57d-99b98e30e12d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
