<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Aceptar_testId-close-cookies-btn</name>
   <tag></tag>
   <elementGuidId>bccf2c24-cdd6-4ed8-9353-fef34c43d8fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='testId-close-cookies-btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#testId-close-cookies-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#testId-close-cookies-btn</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>71807f53-611a-481f-b696-d46b1d771944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>testId-close-cookies-btn</value>
      <webElementGuid>91e788eb-8078-40ed-b0ef-a07fa673f89f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Footer-module_close-legal-banner__Tuqyl</value>
      <webElementGuid>92779805-ee2e-4ef4-9186-463389e49251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;testId-close-cookies-btn&quot;)</value>
      <webElementGuid>3a8d2e33-3a26-4a46-bf9a-7246fd09ecc0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='testId-close-cookies-btn']</value>
      <webElementGuid>b3964344-e657-45d4-9aae-afd494438887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/footer/section[4]/div</value>
      <webElementGuid>32768bfa-5708-4260-8b52-0d9312946531</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[4]/div</value>
      <webElementGuid>6135b529-cf4c-414e-b6e3-11a51611486c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'testId-close-cookies-btn']</value>
      <webElementGuid>3fdbf924-a55c-493c-8eaa-23a2a13f44b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
