<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>67dd79f2-302b-4ff9-8dcb-1f0c796b040d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='asesorOnlineDesktopContainer']/button/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#asesorOnlineDesktopContainer > button > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#asesorOnlineDesktopContainer >> internal:role=button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d43e50ad-2d29-472d-8b6a-66f70c83059a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.falabella.com/static/RDF/site/category/huincha/Asesor/close.svg</value>
      <webElementGuid>5daabbee-d03b-4c15-8362-3b37cd3bb18a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;asesorOnlineDesktopContainer&quot;)/button[1]/img[1]</value>
      <webElementGuid>dd64430b-6db2-4e1e-89bf-cf70995ca3d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='asesorOnlineDesktopContainer']/button/img</value>
      <webElementGuid>3777e465-1d19-4d40-96d1-5a3d0bcb0976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.falabella.com/static/RDF/site/category/huincha/Asesor/close.svg')]</value>
      <webElementGuid>938c8026-e351-4e8a-9e90-1081d5318741</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/button/img</value>
      <webElementGuid>3ee52821-c161-4df3-8b2f-ddcd49f336f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.falabella.com/static/RDF/site/category/huincha/Asesor/close.svg']</value>
      <webElementGuid>ebe294bc-fde7-4963-9747-d5b17cf198c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
