<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Llega hoy</name>
   <tag></tag>
   <elementGuidId>2a027d4e-ae89-4df9-8c23-7223de1e7461</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='LLEGA-HOY-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#LLEGA-HOY-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Llega hoy&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8ef5ca40-7c80-4b24-80fe-c147d70221ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LLEGA-HOY-1</value>
      <webElementGuid>f860fc2b-a465-4fff-a6e3-8f5d4b33f182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d5d494fd-41d2-45ee-b1d2-933ecdee2ac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jsx-3586938503</value>
      <webElementGuid>ab54475c-1331-4882-97d8-3a8d281dc4bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Llega hoy</value>
      <webElementGuid>8816cace-cf9d-41bb-9a0c-9ded1761d92c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LLEGA-HOY-1&quot;)</value>
      <webElementGuid>373963dc-f1be-444f-8d30-e916b23df8a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='LLEGA-HOY-1']</value>
      <webElementGuid>ce3968f6-0558-487c-a2c4-65dc6a05476f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='testId-availability-desktop-container']/div/ul/li/div/div/div/div[2]/div/button</value>
      <webElementGuid>e3fe6356-6d7c-4b0a-8df6-7734bd653ff1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo de Entrega'])[1]/following::button[1]</value>
      <webElementGuid>1c9f6185-fdde-4701-a88c-4f836d408170</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Retira hoy'])[1]/preceding::button[2]</value>
      <webElementGuid>9dd067ff-40c2-4228-96d9-fc6cba2756f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Llega hoy']/parent::*</value>
      <webElementGuid>50105557-18f0-4649-b093-cf079f987c60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>1c24bd68-6033-4428-bb9d-0bd66dd9b1a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'LLEGA-HOY-1' and @type = 'button' and (text() = 'Llega hoy' or . = 'Llega hoy')]</value>
      <webElementGuid>22824e45-137c-4648-b324-477daa817dd6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
