<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Aceptar_testId-close-cookies-btn</name>
   <tag></tag>
   <elementGuidId>f73f31cb-102d-4e56-afe5-e2edb119a36f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#testId-close-cookies-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='testId-close-cookies-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#testId-close-cookies-btn</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>374b944b-3dc2-4ede-9692-62cdf2fd6885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>testId-close-cookies-btn</value>
      <webElementGuid>400eac1d-ecc9-47e6-8e7a-0284164ef85d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Footer-module_close-legal-banner__Tuqyl</value>
      <webElementGuid>5ad15417-9f89-4af1-b919-5727ae8db79b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;testId-close-cookies-btn&quot;)</value>
      <webElementGuid>d7cadf3a-0fb3-4f7f-b877-e0663910be8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='testId-close-cookies-btn']</value>
      <webElementGuid>00fd9eb0-3dec-4075-be44-bc79fdac6900</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/footer/section[4]/div</value>
      <webElementGuid>1fe7e8f3-f3fe-4898-9b1b-31dbcd1dd377</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[4]/div</value>
      <webElementGuid>abcdfc4d-7b30-4a1b-a941-7c8512179b01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'testId-close-cookies-btn']</value>
      <webElementGuid>d013939a-2bb7-47bd-b67f-ea0b37a5a2b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
