<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Aceptar_testId-close-cookies-btn</name>
   <tag></tag>
   <elementGuidId>f73f31cb-102d-4e56-afe5-e2edb119a36f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#testId-close-cookies-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='testId-close-cookies-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#testId-close-cookies-btn</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3359bf35-3113-48c9-a186-1b689cefbb29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>testId-close-cookies-btn</value>
      <webElementGuid>6e964b00-53f2-46a5-94b8-1f05172181d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Footer-module_close-legal-banner__Tuqyl</value>
      <webElementGuid>9c6513df-68b2-47c1-9c4e-8139c70b8a21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;testId-close-cookies-btn&quot;)</value>
      <webElementGuid>7c4e3720-6895-4652-953c-00f8d42e903a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='testId-close-cookies-btn']</value>
      <webElementGuid>1ee5709e-eaf6-46d4-98e8-ca4749ce484c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/footer/section[4]/div</value>
      <webElementGuid>a8d24ad2-b736-425c-9fe7-43734790eddd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[4]/div</value>
      <webElementGuid>deec74fa-6ec7-4aa9-bc70-b99074ece625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'testId-close-cookies-btn']</value>
      <webElementGuid>c269f95c-722c-4722-9815-ffff72aa5bae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
