<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Agregar al Carro_testId-pod-image-https_278362</name>
   <tag></tag>
   <elementGuidId>b9408ef5-9f32-4ffe-ac2d-6660fa6d7dfd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//img[@id='testId-pod-image-https://media.falabella.com.pe/falabellaPE/18673460_1/public'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;APPLE - IPhone 13 128GB APPLE IPhone 13 128GB Por Falabella S/ 1,899 -57% S/ 2,099 S/ 4,399 Llega mañana Retira mañana Envío en 180 minutos      (1783) Agregar al Carro&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>dc351d8b-aa95-438d-8159-2361267beb81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://media.falabella.com.pe/falabellaPE/18673460_1/width=240,height=240,quality=70,format=webp,fit=pad</value>
      <webElementGuid>21fb4be4-f86e-4073-8cc5-16727707be53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://media.falabella.com.pe/falabellaPE/18673460_1/width=480,height=480,quality=70,format=webp,fit=pad 2x</value>
      <webElementGuid>03153aba-116a-48a2-af17-7701341ba70e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>APPLE - IPhone 13 128GB</value>
      <webElementGuid>3cd409b7-bba4-474a-91af-df8157867b80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>testId-pod-image-https://media.falabella.com.pe/falabellaPE/18673460_1/public</value>
      <webElementGuid>147de9b2-25cd-4bd9-868b-df70dbf3d3de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>240</value>
      <webElementGuid>13709277-356d-49e2-8f01-cb0c20b1cfab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>240</value>
      <webElementGuid>0d71826d-ed38-407e-9f04-1dbddb489342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jsx-1996933093</value>
      <webElementGuid>ee3b708f-42b3-4e15-96b2-f710e2330a53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;testId-pod-18673460&quot;)/div[@class=&quot;jsx-4134261027 jsx-3390574944 pod-head&quot;]/div[@class=&quot;jsx-1273315118&quot;]/section[@class=&quot;jsx-1273315118 image--active layout_grid-view layout_view_4_GRID&quot;]/picture[@class=&quot;jsx-1996933093&quot;]/img[@id=&quot;testId-pod-image-https://media.falabella.com.pe/falabellaPE/18673460_1/public&quot;]</value>
      <webElementGuid>170d604d-7b2d-4710-8cfa-842f0c7e9e76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//img[@id='testId-pod-image-https://media.falabella.com.pe/falabellaPE/18673460_1/public'])[2]</value>
      <webElementGuid>5fb76a73-a9c2-4022-9085-07b2ad4a9df8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='testId-pod-18673460']/div/div/section/picture/img</value>
      <webElementGuid>84127097-056b-4db1-83a9-0894bac427b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='APPLE - IPhone 13 128GB'])[6]</value>
      <webElementGuid>5762df73-cf85-4e0e-a81d-aad51980a46d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/div/div/section/picture/img</value>
      <webElementGuid>e9e91673-065f-4be7-8164-aaeb49a51685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://media.falabella.com.pe/falabellaPE/18673460_1/width=240,height=240,quality=70,format=webp,fit=pad' and @alt = 'APPLE - IPhone 13 128GB' and @id = 'testId-pod-image-https://media.falabella.com.pe/falabellaPE/18673460_1/public']</value>
      <webElementGuid>7a66b0ad-b3ff-4bcd-9486-360fb03b69a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
