<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__testId-pod-image-httpsmedia.falabella._9511bf</name>
   <tag></tag>
   <elementGuidId>c8f22838-cb92-43a3-a17d-df017f23ed21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//img[@id='testId-pod-image-https://media.falabella.com.pe/tottusPE/43556162_1/public'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;MOTOROLA - Smartphone G56 8+256Gb Azul Marino MOTOROLA Smartphone G56 8+256Gb Azul Marino Por Tottus S/ 679 -28% S/ 699 S/ 949 Patrocinado Agregar al Carro&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6352421b-e818-4f7b-aeda-8efba7ac96d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://media.falabella.com.pe/tottusPE/43556162_1/width=240,height=240,quality=70,format=webp,fit=pad</value>
      <webElementGuid>2e666ed5-76de-4f8f-852d-03d109db1275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://media.falabella.com.pe/tottusPE/43556162_1/width=480,height=480,quality=70,format=webp,fit=pad 2x</value>
      <webElementGuid>84afa67a-08a1-4826-a133-225ae3bd265a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>MOTOROLA - Smartphone G56 8+256Gb Azul Marino</value>
      <webElementGuid>4d89c3cb-14a2-4d98-9e5e-29505568c712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>testId-pod-image-https://media.falabella.com.pe/tottusPE/43556162_1/public</value>
      <webElementGuid>9ccfd678-d9c3-4ed6-b42b-cf6cf914da9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>240</value>
      <webElementGuid>3bd80e9a-86ea-4299-97ad-9beec6a9803c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>240</value>
      <webElementGuid>d58fc95d-a6c0-478c-9a8a-3daec8e74998</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fetchpriority</name>
      <type>Main</type>
      <value>high</value>
      <webElementGuid>feee51f9-a124-469d-8415-33406e14aeed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jsx-1996933093</value>
      <webElementGuid>42a8e4d1-c15d-4ac6-82c9-f1ff6ed2954e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;testId-pod-146172452&quot;)/div[@class=&quot;jsx-4134261027 jsx-3390574944 pod-head&quot;]/div[@class=&quot;jsx-1273315118&quot;]/section[@class=&quot;jsx-1273315118 image--active layout_grid-view layout_view_4_GRID&quot;]/picture[@class=&quot;jsx-1996933093&quot;]/img[@id=&quot;testId-pod-image-https://media.falabella.com.pe/tottusPE/43556162_1/public&quot;]</value>
      <webElementGuid>42337028-3793-4daf-b9f8-1f21974e94b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//img[@id='testId-pod-image-https://media.falabella.com.pe/tottusPE/43556162_1/public'])[2]</value>
      <webElementGuid>ed5a273c-7a55-4950-836d-61e20f654062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='testId-pod-146172452']/div/div/section/picture/img</value>
      <webElementGuid>5b94e258-b89e-49dd-875a-95fbfe0f5be4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='MOTOROLA - Smartphone G56 8+256Gb Azul Marino'])[6]</value>
      <webElementGuid>6389fd9e-526b-4eaf-9161-5da7a31693c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/picture/img</value>
      <webElementGuid>6d4fdc93-1836-4c84-b14f-551815d32a4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://media.falabella.com.pe/tottusPE/43556162_1/width=240,height=240,quality=70,format=webp,fit=pad' and @alt = 'MOTOROLA - Smartphone G56 8+256Gb Azul Marino' and @id = 'testId-pod-image-https://media.falabella.com.pe/tottusPE/43556162_1/public']</value>
      <webElementGuid>e4b81b2a-07a4-411a-b37f-2fd20bbb8414</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
