<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Agregar al Carro_testId-pod-image-https_79bcc9</name>
   <tag></tag>
   <elementGuidId>bb7532f9-7bfe-4f91-ac9b-c9ad481d3810</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//img[@id='testId-pod-image-https://media.falabella.com.pe/falabellaPE/20039958_01/public'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;APPLE - Iphone 15 128Gb APPLE Iphone 15 128Gb Por Falabella S/ 3,099 -38% S/ 3,199 S/ 4,999 Llega mañana Retira mañana Envío en 180 minutos      (26) Agregar al Carro&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1db5de08-07ce-4a58-bd38-4baebd5f0ed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://media.falabella.com.pe/falabellaPE/20039958_01/width=240,height=240,quality=70,format=webp,fit=pad</value>
      <webElementGuid>8ca6ed35-b7b2-435b-b52a-cc016e40c444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://media.falabella.com.pe/falabellaPE/20039958_01/width=480,height=480,quality=70,format=webp,fit=pad 2x</value>
      <webElementGuid>d97eb489-92cc-4bcb-8005-17c11cf15e03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>APPLE - Iphone 15 128Gb</value>
      <webElementGuid>4edaed33-d05f-4eaa-b61e-1c8fc3088d2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>testId-pod-image-https://media.falabella.com.pe/falabellaPE/20039958_01/public</value>
      <webElementGuid>e03dadb5-d257-4e02-b096-4f41b0539833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>240</value>
      <webElementGuid>50da76a5-8b4d-42e0-b22a-3109f3c5e04e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>240</value>
      <webElementGuid>951b3ee3-8ffd-4205-9e55-d990f7dd660d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jsx-1996933093</value>
      <webElementGuid>1482aad3-b1f1-4d85-9c1f-2e06a14649ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;testId-pod-20039958&quot;)/div[@class=&quot;jsx-4134261027 jsx-3390574944 pod-head&quot;]/div[@class=&quot;jsx-1273315118&quot;]/section[@class=&quot;jsx-1273315118 image--active layout_grid-view layout_view_4_GRID&quot;]/picture[@class=&quot;jsx-1996933093&quot;]/img[@id=&quot;testId-pod-image-https://media.falabella.com.pe/falabellaPE/20039958_01/public&quot;]</value>
      <webElementGuid>bad6d887-d053-48f9-9b05-82529d9b85db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//img[@id='testId-pod-image-https://media.falabella.com.pe/falabellaPE/20039958_01/public'])[2]</value>
      <webElementGuid>2d2e396e-6c17-41c7-a492-21db232be4af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='testId-pod-20039958']/div/div/section/picture/img</value>
      <webElementGuid>71e7e855-e3c4-47bd-b3c4-2b19bcfc77d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='APPLE - Iphone 15 128Gb'])[6]</value>
      <webElementGuid>5fa4b8ef-1fcb-4de5-8890-7405ec9f1fff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a/div/div/section/picture/img</value>
      <webElementGuid>3234df7c-f0a1-4ba4-9361-374656832386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://media.falabella.com.pe/falabellaPE/20039958_01/width=240,height=240,quality=70,format=webp,fit=pad' and @alt = 'APPLE - Iphone 15 128Gb' and @id = 'testId-pod-image-https://media.falabella.com.pe/falabellaPE/20039958_01/public']</value>
      <webElementGuid>41692af4-0e05-4c99-97e0-e6c989d3c4d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
