<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__testId-pod-image-httpsmedia.falabella._9511bf (1)</name>
   <tag></tag>
   <elementGuidId>66624b08-8b70-4022-baf6-7b67491c0bda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//img[@id='testId-pod-image-https://media.falabella.com.pe/tottusPE/43556162_1/public'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;MOTOROLA - Smartphone G56 8+256Gb Azul Marino MOTOROLA Smartphone G56 8+256Gb Azul Marino Por Tottus S/ 679 -28% S/ 699 S/ 949 Patrocinado Agregar al Carro&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4cab4c70-2501-41c7-b927-a7a9c91d9129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://media.falabella.com.pe/tottusPE/43556162_1/width=240,height=240,quality=70,format=webp,fit=pad</value>
      <webElementGuid>cdf86ca7-309d-4350-9ab2-898eeca8600f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://media.falabella.com.pe/tottusPE/43556162_1/width=480,height=480,quality=70,format=webp,fit=pad 2x</value>
      <webElementGuid>f91140a0-fb6d-4564-ae16-7d9d243179ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>MOTOROLA - Smartphone G56 8+256Gb Azul Marino</value>
      <webElementGuid>e85c84da-c901-4d2d-b106-ed7fe6dd8b95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>testId-pod-image-https://media.falabella.com.pe/tottusPE/43556162_1/public</value>
      <webElementGuid>20a02216-d2b3-4ed2-af40-7fc8549d0b9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>240</value>
      <webElementGuid>27c7d2dc-4704-4d81-a78d-6e2b1ce7173e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>240</value>
      <webElementGuid>be4d6354-e2a4-49d4-ba84-43c9f3ad1983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fetchpriority</name>
      <type>Main</type>
      <value>high</value>
      <webElementGuid>2a71ba06-4a58-418d-9785-aea4c69a8d8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jsx-1996933093</value>
      <webElementGuid>76a4b20e-7ad3-4d1e-ac75-fa9c2688bced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;testId-pod-146172452&quot;)/div[@class=&quot;jsx-4134261027 jsx-3390574944 pod-head&quot;]/div[@class=&quot;jsx-1273315118&quot;]/section[@class=&quot;jsx-1273315118 image--active layout_grid-view layout_view_4_GRID&quot;]/picture[@class=&quot;jsx-1996933093&quot;]/img[@id=&quot;testId-pod-image-https://media.falabella.com.pe/tottusPE/43556162_1/public&quot;]</value>
      <webElementGuid>17ac20ba-6482-4eed-a4ff-86ed1220f552</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//img[@id='testId-pod-image-https://media.falabella.com.pe/tottusPE/43556162_1/public'])[2]</value>
      <webElementGuid>f15bd938-306b-4016-8ddc-2af0bc8dcf9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='testId-pod-146172452']/div/div/section/picture/img</value>
      <webElementGuid>51db7432-3435-4823-a948-8662e8756ec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='MOTOROLA - Smartphone G56 8+256Gb Azul Marino'])[6]</value>
      <webElementGuid>881194cc-d447-4d5f-add3-ce7dcf899cc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/picture/img</value>
      <webElementGuid>bd02153a-9b76-4961-b0c7-d1d287b37f26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://media.falabella.com.pe/tottusPE/43556162_1/width=240,height=240,quality=70,format=webp,fit=pad' and @alt = 'MOTOROLA - Smartphone G56 8+256Gb Azul Marino' and @id = 'testId-pod-image-https://media.falabella.com.pe/tottusPE/43556162_1/public']</value>
      <webElementGuid>2d8b67f0-4fd7-465e-bf06-f41456a0bf95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
