<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Agregar al Carro_testId-pod-image-https_1a8e5d</name>
   <tag></tag>
   <elementGuidId>129c42e3-cfe7-4df9-89dc-0fa743ff95ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//img[@id='testId-pod-image-https://media.falabella.com.pe/falabellaPE/18673461_1/public'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;APPLE - IPhone 13 128GB APPLE IPhone 13 128GB Por Falabella S/ 1,899 -57% S/ 1,999 S/ 4,399 Llega mañana Retira hoy 18Cuotas Sin Interes CMR      (1788) Agregar al Carro&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a9e9aed5-a2dd-46c6-8376-f2c85f7fd99f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://media.falabella.com.pe/falabellaPE/18673461_1/width=240,height=240,quality=70,format=webp,fit=pad</value>
      <webElementGuid>82e76313-792b-4cb9-8c84-23d8d98825b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://media.falabella.com.pe/falabellaPE/18673461_1/width=480,height=480,quality=70,format=webp,fit=pad 2x</value>
      <webElementGuid>8fbbb510-266d-471a-a6a5-f1b379629da7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>APPLE - IPhone 13 128GB</value>
      <webElementGuid>72eed8da-8dbb-4377-8197-144ada11db04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>testId-pod-image-https://media.falabella.com.pe/falabellaPE/18673461_1/public</value>
      <webElementGuid>3bb9c51a-24cd-4228-b558-7c4e3c0f1149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>240</value>
      <webElementGuid>4808acd4-5572-4cce-a02d-4390762cc609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>240</value>
      <webElementGuid>be1e5f3b-b8a9-4f75-9336-72337f096035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jsx-1996933093</value>
      <webElementGuid>e96f074f-732d-4399-841e-df62fe67f0e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;testId-pod-18673461&quot;)/div[@class=&quot;jsx-4134261027 jsx-3390574944 pod-head&quot;]/div[@class=&quot;jsx-1273315118&quot;]/section[@class=&quot;jsx-1273315118 image--active layout_grid-view layout_view_4_GRID&quot;]/picture[@class=&quot;jsx-1996933093&quot;]/img[@id=&quot;testId-pod-image-https://media.falabella.com.pe/falabellaPE/18673461_1/public&quot;]</value>
      <webElementGuid>f9d1e2eb-1873-43c3-8522-1ee955b3f36b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//img[@id='testId-pod-image-https://media.falabella.com.pe/falabellaPE/18673461_1/public'])[2]</value>
      <webElementGuid>df28f3c1-b50e-4d5d-ab9c-8c9577dde357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='testId-pod-18673461']/div/div/section/picture/img</value>
      <webElementGuid>9ad83866-0e98-4495-84ef-4b5d0e14e483</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='APPLE - IPhone 13 128GB'])[6]</value>
      <webElementGuid>1e3d09fe-afd0-48ef-87ab-73185cf6f2cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/div/div/section/picture/img</value>
      <webElementGuid>cc0511e9-3732-451e-892f-d6358ab2d523</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://media.falabella.com.pe/falabellaPE/18673461_1/width=240,height=240,quality=70,format=webp,fit=pad' and @alt = 'APPLE - IPhone 13 128GB' and @id = 'testId-pod-image-https://media.falabella.com.pe/falabellaPE/18673461_1/public']</value>
      <webElementGuid>2a6106a6-d898-483b-a9b5-a4d78f51807b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
