<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_S 500 - s 1.000_S-1.000---S-2.000-1998</name>
   <tag></tag>
   <elementGuidId>4d8926d8-784e-4d4c-89ff-b886e04e62cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='S/-1.000---S/-2.000-1998']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;S/ 1.000 - s/ 2.000&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0b8a1069-666d-4513-967e-9ecaa121e407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>S/-1.000---S/-2.000-1998</value>
      <webElementGuid>507cc82c-5cfd-4ac1-9428-f3ff21f40cc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>85d216a7-ef0d-4c87-a76b-124111c5eb8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jsx-2981097851 input-checkbox</value>
      <webElementGuid>c272d8c1-abdf-44b0-acf6-be6f23a1bd1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;S/-1.000---S/-2.000-1998&quot;)</value>
      <webElementGuid>b42b041c-d72d-49cb-8767-a0bdaf43f689</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='S/-1.000---S/-2.000-1998']</value>
      <webElementGuid>dc250bd3-f1a2-4f69-9893-d49a0bf69b55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='S/-1.000---S/-2.000-1998-wrapper']/input</value>
      <webElementGuid>d12f00cc-3305-4135-96d3-4bd467a15956</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/label/input</value>
      <webElementGuid>249857d4-66f6-481c-a522-3845b47b61e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'S/-1.000---S/-2.000-1998' and @type = 'checkbox']</value>
      <webElementGuid>145651b4-aecd-4d5d-8803-6f4a3ce63d97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
