<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_negro</name>
   <tag></tag>
   <elementGuidId>f2728f50-5e50-48c4-82ff-2d72ea08d27b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//span[@id=''])[39]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.jsx-3350276935.jsx-4009666696.title > span.title1.primary.jsx-233704000.bold</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;negro&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>75b09783-0310-46c0-a1c8-c03fa2a58e7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title1 primary  jsx-233704000 bold        </value>
      <webElementGuid>28f77165-8a61-42c9-9ae6-67b876d31c1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>negro</value>
      <webElementGuid>656eef0d-319f-44bc-9ddf-5d28d6c7f2dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;testId-multiSelectForColor-negro&quot;)/label[@class=&quot;jsx-3350276935 jsx-4009666696 checkbox&quot;]/div[@class=&quot;jsx-3350276935 jsx-4009666696 title&quot;]/span[@class=&quot;title1 primary  jsx-233704000 bold&quot;]</value>
      <webElementGuid>a4847193-5909-48d6-a650-b858eb0ec06c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//span[@id=''])[39]</value>
      <webElementGuid>c0dea8af-ca9c-4a72-a644-25355d6bcddc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='testId-multiSelectForColor-negro']/label/div/span</value>
      <webElementGuid>c4aaefbc-88b9-469c-8da5-4663a0a7e297</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='naranjo'])[1]/following::span[1]</value>
      <webElementGuid>f6661c86-19bc-4c92-885d-7ce041d2cb0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='morado'])[1]/following::span[2]</value>
      <webElementGuid>66dec8ef-725d-489c-8535-8f9e47d9b411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='plateado'])[1]/preceding::span[1]</value>
      <webElementGuid>b584c911-504c-4abc-8c59-105f8d9b4016</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='rojo'])[1]/preceding::span[2]</value>
      <webElementGuid>31e4be18-7694-43a6-884c-31ee9e2a2e2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='negro']/parent::*</value>
      <webElementGuid>2f5b563a-9585-42a2-9bb2-b69a3b3b6c24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[11]/label/div/span</value>
      <webElementGuid>0024e5b6-a573-43ec-bc51-4afb155bd9f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'negro' or . = 'negro')]</value>
      <webElementGuid>4a32d776-4d30-40c8-b2bb-b24351ee61a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
