<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_celulares baratos</name>
   <tag></tag>
   <elementGuidId>9fa912c8-9b53-4148-a5e9-ebc169a559b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.SearchList-module_searchListItem__active__evqSW</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='testId-search-wrapper']/div[3]/section/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;celulares baratos&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0c7c7901-9bba-4301-aca1-d9d31067e68c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>SearchList-module_searchListItem__active__evqSW</value>
      <webElementGuid>147bc49c-e116-4542-8a9f-85b24098cbde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>b6cecbd3-f1f7-4055-b438-193822c8e8a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.falabella.com.pe/falabella-pe/search?Ntt=celulares+baratos</value>
      <webElementGuid>cbd6990d-d585-48b7-b78a-68ed779ed39e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>celulares baratos</value>
      <webElementGuid>bd081f29-2fb1-4880-b331-bbcb6d6cd49c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;testId-search-wrapper&quot;)/div[@class=&quot;SearchList-module_searchResults__MeS7t&quot;]/section[1]/ul[1]/li[@class=&quot;SearchList-module_searchListItem__JYqjK&quot;]/a[@class=&quot;SearchList-module_searchListItem__active__evqSW&quot;]</value>
      <webElementGuid>f7cbe429-202a-4c47-95bc-d67a9e64be23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='testId-search-wrapper']/div[3]/section/ul/li[3]/a</value>
      <webElementGuid>abc84f23-7c4c-407f-a669-a36c5888b853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='celular'])[2]/following::a[1]</value>
      <webElementGuid>febd6119-41a2-4bc7-b673-eaaf1388950f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='es baratos']/parent::*</value>
      <webElementGuid>f01b2036-8b2a-4a23-896d-c85d23b568cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.falabella.com.pe/falabella-pe/search?Ntt=celulares+baratos')]</value>
      <webElementGuid>3bac4fb1-76c4-4954-8184-9ca46645cea9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>bbf64b1d-7fec-49ed-8106-3b7347dd9df1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.falabella.com.pe/falabella-pe/search?Ntt=celulares+baratos' and (text() = 'celulares baratos' or . = 'celulares baratos')]</value>
      <webElementGuid>933c5820-5450-4d62-9c11-4737789fac62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='celu'])[2]/following::a[1]</value>
      <webElementGuid>dfffdf92-78bf-4efd-b0a2-2de0b41d0a98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='lares baratos']/parent::*</value>
      <webElementGuid>e99931af-3326-404c-8abc-82204969183f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
