<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_laptop</name>
   <tag></tag>
   <elementGuidId>4c2346dd-c97c-42d6-a6b2-b57bc9c9519f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='testId-search-wrapper']/div[3]/section/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.SearchList-module_searchListItem__active__evqSW</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;laptop&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>eb21f4d4-3a60-4fd4-8d27-b2282bc96b6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>SearchList-module_searchListItem__active__evqSW</value>
      <webElementGuid>bc8f539b-e2fa-4592-96ae-a31c9e7769f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>6857f0b5-8164-4920-81d3-a0ee02aa418b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.falabella.com.pe/falabella-pe/search?Ntt=laptop</value>
      <webElementGuid>85c09d91-255b-41a8-ac23-5ce5c275a840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>laptop</value>
      <webElementGuid>c3f55b0e-3089-4f0d-8d41-f4fdb6588ec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;testId-search-wrapper&quot;)/div[@class=&quot;SearchList-module_searchResults__MeS7t&quot;]/section[1]/ul[1]/li[@class=&quot;SearchList-module_searchListItem__JYqjK&quot;]/a[@class=&quot;SearchList-module_searchListItem__active__evqSW&quot;]</value>
      <webElementGuid>d1838ade-b5de-4e1b-b487-ab3b2ad002b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='testId-search-wrapper']/div[3]/section/ul/li/a</value>
      <webElementGuid>02e02726-cb56-4a4d-bc3a-5fb5b11f743a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search Bar'])[1]/following::a[1]</value>
      <webElementGuid>b751ef41-cde2-45c5-a832-17e4084b5a5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menú'])[1]/following::a[1]</value>
      <webElementGuid>28a6983d-0ae2-4f3c-a7fc-9e1fe1502489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='top']/parent::*</value>
      <webElementGuid>f026ec4b-2da3-4f66-896e-eb732b857204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.falabella.com.pe/falabella-pe/search?Ntt=laptop')]</value>
      <webElementGuid>59533dfd-85aa-4821-8d39-6902c7bb55a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>16f192a4-2bd9-4a9f-b887-0498a0e96b22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.falabella.com.pe/falabella-pe/search?Ntt=laptop' and (text() = 'laptop' or . = 'laptop')]</value>
      <webElementGuid>bebcb58d-540b-46fe-aa57-ed4b12b2f95c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
