<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Tecnologa</name>
   <tag></tag>
   <elementGuidId>3997b6bf-479d-4b3c-9d3c-5de30741776f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='scrollable-content']/div/div[2]/div/div[2]/div/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.SecondLevelCategories-module_title__HhC8K</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;header-util-bar&quot;] >> internal:role=link[name=&quot;Tecnología&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6e711c89-2492-4708-8d17-f3e702883905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noreferrer noopener</value>
      <webElementGuid>44540a3b-996b-47eb-bdd5-95f30cabdc14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>d5258d51-887f-4c7a-81e9-9ea2dd30751c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>SecondLevelCategories-module_title__HhC8K</value>
      <webElementGuid>f1909262-518b-486e-add2-5d023a51159a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.falabella.com.pe/falabella-pe/category/cat40793/Tecnologia</value>
      <webElementGuid>e46606ae-e249-4269-85a0-6e92c82b8562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tecnología</value>
      <webElementGuid>c794d22b-6f88-4b94-a3de-82fdc9b61a59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scrollable-content&quot;)/div[@class=&quot;Header-module_container__8x1TS Header-module_header-container__UoP9n&quot;]/div[@class=&quot;Taxonomy-module_HamburgerBtnWrapper__oNEG4&quot;]/div[@class=&quot;TaxonomyDesktop-module_TaxonomyDesktop__Ihty- sidebar-open-enter-done&quot;]/div[@class=&quot;SecondLevelCategories-module_secondLevelMenuContainer__I3RRy&quot;]/div[@class=&quot;SecondLevelCategories-module_scrollContainer__3kQqe&quot;]/div[@class=&quot;SecondLevelCategories-module_subCategoryMainTitleWrapper__7mxw-&quot;]/div[@class=&quot;SecondLevelCategories-module_subCategoryMainTitle__X3kZG&quot;]/a[@class=&quot;SecondLevelCategories-module_title__HhC8K&quot;]</value>
      <webElementGuid>4eb2d6f7-2c07-4f07-8fce-c3620f7b3e5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scrollable-content']/div/div[2]/div/div[2]/div/div/div/a</value>
      <webElementGuid>d1c95a4e-561a-4141-a067-2f6b627a42f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Tecnología')]</value>
      <webElementGuid>8bd0f8a7-f583-4e3c-9e3a-df23834d0614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seguros'])[1]/following::a[2]</value>
      <webElementGuid>c83ffebf-41ed-412c-a69c-bac46d890e79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Horario de tiendas'])[1]/following::a[3]</value>
      <webElementGuid>760ff3db-05cf-484e-b7a6-e7fa24ffa09c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver todo'])[1]/preceding::a[1]</value>
      <webElementGuid>c5325a1e-0e9f-476e-ad38-f62e06737af7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Celulares'])[1]/preceding::a[2]</value>
      <webElementGuid>30c09a43-5dc9-47a2-ba1d-8b423e720435</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.falabella.com.pe/falabella-pe/category/cat40793/Tecnologia')]</value>
      <webElementGuid>63d63fed-8c37-450b-b11a-281baac8d659</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div[2]/div/div/div/a</value>
      <webElementGuid>9c6079fa-984c-4a7a-a231-60c851ff6115</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.falabella.com.pe/falabella-pe/category/cat40793/Tecnologia' and (text() = 'Tecnología' or . = 'Tecnología')]</value>
      <webElementGuid>d69df5b6-a819-45f3-8915-4991fef0d7b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
