<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Aceptar_airship-html-prompt-shadow-ad 2025-b68</name>
   <tag></tag>
   <elementGuidId>cfab9187-9ff9-445e-9a4f-89b09d795343</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.airship-html-prompt-shadow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=&quot;Airship ¿Quieres conocer las mejores ofertas? Que nadie te lo cuente. Suscríbete&quot;i >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c95b49a7-fdfa-4196-9a9d-b55b10e3998e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>airship-html-prompt-shadow</value>
      <webElementGuid>100bad3d-c4c3-4d3a-a407-e6d858dfd946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;airship-html-prompt-shadow&quot;]</value>
      <webElementGuid>e0bcb888-948c-45dd-bc13-f7764d10f30c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]</value>
      <webElementGuid>e87759be-9184-4f3d-8bc8-531953808fa6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
