<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_concat(id(, , main-Banner-90c27cca-50d0_d0c05f</name>
   <tag></tag>
   <elementGuidId>8a15097c-60ae-445a-9869-f2503cfa07c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.airship-html-prompt-shadow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=&quot;Airship ¿Quieres conocer las mejores ofertas? Que nadie te lo cuente. Suscríbete&quot;i >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2e183aab-5063-4dd2-bfa0-12161d9642df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>airship-html-prompt-shadow</value>
      <webElementGuid>4a0904ff-bf16-427f-970c-d0ac20d26524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;airship-html-prompt-shadow&quot;]</value>
      <webElementGuid>94f735d7-8fab-42cf-9872-3719e96803dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]</value>
      <webElementGuid>281dd671-03d3-4a5a-9cbf-a32e2dfd4e4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
