<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_compras_UserActions-module_utilIcon__CMvmc</name>
   <tag></tag>
   <elementGuidId>6d248664-3924-48db-b30e-1aeaf2a25245</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='testId-UserAction-basket']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#testId-UserAction-basket > i.UserActions-module_utilIcon__CMvmc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#testId-UserAction-basket</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>891d6b23-f867-47b3-9a75-34b9524d4210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>UserActions-module_utilIcon__CMvmc</value>
      <webElementGuid>95af89cf-1760-4ed8-b5f9-2384ddf98cae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;testId-UserAction-basket&quot;)/i[@class=&quot;UserActions-module_utilIcon__CMvmc&quot;]</value>
      <webElementGuid>d2ff734c-6a8b-4a84-bbcb-24aba98700df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='testId-UserAction-basket']/i</value>
      <webElementGuid>7aac90e7-5224-487f-a333-9dc6b1dbfcdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/a/i</value>
      <webElementGuid>6ad41cf3-f1c4-4714-8abb-7f85016b5561</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
