<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Search Bar_SearchBar-module_searchIcon__-gxub</name>
   <tag></tag>
   <elementGuidId>bcbf5014-0a62-4180-808e-7a40b1b1e130</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='testId-search-wrapper']/div/button/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.SearchBar-module_searchIcon__-gxub</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Search Bar&quot;i] >> internal:role=button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2073ce2e-1045-434b-9630-6f123542212e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>SearchBar-module_searchIcon__-gxub</value>
      <webElementGuid>fe8e0ac5-42bf-4bdc-9463-35da5c815c55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://images.falabella.com/v3/assets/bltf4ed0b9a176c126e/blt60499304f5cc381c/6213f2df23d8fd714a7a43be/hr-3-search-desktop.svg</value>
      <webElementGuid>19af77e5-3ce1-459f-8ef2-98561ae543b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;testId-search-wrapper&quot;)/div[@class=&quot;SearchBar-module_searchBarWrapper__NPHoF&quot;]/button[@class=&quot;SearchBar-module_searchBtnIcon__YqTAF&quot;]/img[@class=&quot;SearchBar-module_searchIcon__-gxub&quot;]</value>
      <webElementGuid>8bd386d9-63c0-4f0d-83e0-ee649802243e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='testId-search-wrapper']/div/button/img</value>
      <webElementGuid>ae50a619-f80b-499a-94db-1a44ee5b93d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://images.falabella.com/v3/assets/bltf4ed0b9a176c126e/blt60499304f5cc381c/6213f2df23d8fd714a7a43be/hr-3-search-desktop.svg')]</value>
      <webElementGuid>43031217-5950-4591-b3d3-f9c6b36fcd49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/img</value>
      <webElementGuid>5cdcb3ed-7067-440f-98e9-d5c5afd6dca4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://images.falabella.com/v3/assets/bltf4ed0b9a176c126e/blt60499304f5cc381c/6213f2df23d8fd714a7a43be/hr-3-search-desktop.svg']</value>
      <webElementGuid>0e94cb05-c5be-425c-b610-705da4678503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='testId-search-wrapper']/div[2]/button/img</value>
      <webElementGuid>f4dcaa3c-4484-458d-bbf3-0ba1a6cca963</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
