<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Search Bar_SearchBar-module_searchIcon__-gxub</name>
   <tag></tag>
   <elementGuidId>bcbf5014-0a62-4180-808e-7a40b1b1e130</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='testId-search-wrapper']/div[2]/button/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.SearchBar-module_searchIcon__-gxub</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Search Bar laptop en Laptops en Computación gamer en Parlantes Bluetooth laptops laptop gamer laptop lenovo laptop hp laptop asus laptop i7 laptop acer laptops gamer laptop apple Marcas relacionadas LENOVO ASUS HP APPLE SAMSUNG ACER LG XIAOMI MOTOROLA DELL Categorías relacionadas Laptops Computación gamer Parlantes Bluetooth Accesorios Computación Accesorios Celulares Accesorios Accesorios Almacenamiento Audífonos Accesorios audio&quot;i] >> internal:role=button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>95dcce0d-6083-4e79-ab04-4b0cc76437ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>SearchBar-module_searchIcon__-gxub</value>
      <webElementGuid>4a10d3f6-7c06-4f4d-9005-16b5595ece21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://images.falabella.com/v3/assets/bltf4ed0b9a176c126e/blt60499304f5cc381c/6213f2df23d8fd714a7a43be/hr-3-search-desktop.svg</value>
      <webElementGuid>71b39802-cd2d-4a1a-8183-0d4e900ada34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;testId-search-wrapper&quot;)/div[@class=&quot;SearchBar-module_searchBarWrapper__NPHoF&quot;]/button[@class=&quot;SearchBar-module_searchBtnIcon__YqTAF SearchBar-module_showFlatEdges__rvQ-3 SearchBar-module_overlap__5JWUe&quot;]/img[@class=&quot;SearchBar-module_searchIcon__-gxub&quot;]</value>
      <webElementGuid>2f364a06-e748-4bed-9ef0-ec0041b345bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='testId-search-wrapper']/div[2]/button/img</value>
      <webElementGuid>f4dcaa3c-4484-458d-bbf3-0ba1a6cca963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://images.falabella.com/v3/assets/bltf4ed0b9a176c126e/blt60499304f5cc381c/6213f2df23d8fd714a7a43be/hr-3-search-desktop.svg')]</value>
      <webElementGuid>57473057-1ecd-4fe3-8cf1-b2385ae6c283</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/img</value>
      <webElementGuid>28a84821-7c42-4e1e-bcba-6221d1aef307</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://images.falabella.com/v3/assets/bltf4ed0b9a176c126e/blt60499304f5cc381c/6213f2df23d8fd714a7a43be/hr-3-search-desktop.svg']</value>
      <webElementGuid>a399da77-81ea-4106-b6f4-d4dddac9c6df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
