<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search Bar_testId-SearchBar-Input</name>
   <tag></tag>
   <elementGuidId>fe932e70-fb96-4363-a289-211cda771670</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#testId-SearchBar-Input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='testId-SearchBar-Input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Buscar en falabella.com&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>48c81a64-50ef-42d0-b1e7-b68e85e28b0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>66179a3a-6307-4208-9f5d-c84770caeee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>SearchBar-module_searchBar__Input__NDqpk</value>
      <webElementGuid>07d7f119-6ca5-4aff-95e7-79f2bbef98df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>testId-SearchBar-Input</value>
      <webElementGuid>30d78b40-caf6-493d-b5f5-85bd2ee950bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>8cc87b18-1e6b-4538-82a8-79d67a712524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d9c4b9a1-cb5a-4133-a922-4b96e1ec147d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Buscar en falabella.com</value>
      <webElementGuid>39ccba71-6705-41b5-9361-3572f8f52637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;testId-SearchBar-Input&quot;)</value>
      <webElementGuid>d6336eed-5031-438c-828e-c6156d2a9d19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='testId-SearchBar-Input']</value>
      <webElementGuid>d682fd66-e5ab-400b-8537-b3da109a8fe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='testId-search-wrapper']/div/div/input</value>
      <webElementGuid>908619d1-545e-4789-be87-09ea0a3b9399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>535ea833-99d4-4f2c-be66-f17cc1dc2222</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'testId-SearchBar-Input' and @type = 'text' and @placeholder = 'Buscar en falabella.com']</value>
      <webElementGuid>595bd31d-d461-45e2-a27b-7ed7f2312810</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
