<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Correo electrnico_testId-cc-login-for_d0c7d1</name>
   <tag></tag>
   <elementGuidId>7d04e84e-e3d8-43f4-87f4-3382bccd7dcb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='testId-cc-login-form-email-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#testId-cc-login-form-email-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Ingresa tu correo electrónico&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eb5049f2-1ee2-4487-bd37-b88f223f616a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>testId-cc-login-form-email-input</value>
      <webElementGuid>551297da-a3ba-4add-9103-b66f42227296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>44200f6c-9faf-4964-8c51-dc01547452fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>645e212f-2eba-4bae-9ffb-997af112558d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ingresa tu correo electrónico</value>
      <webElementGuid>ae4f2ccf-810c-42d9-a62e-3b16193399e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-field-module_field-input__2sh6Y</value>
      <webElementGuid>cd6a3471-7f45-4178-a6c8-071c955fc776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>J</value>
      <webElementGuid>f8cc6603-1796-470c-ba28-fc09dfcc84c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;testId-cc-login-form-email-input&quot;)</value>
      <webElementGuid>f2e26b6a-35d1-423a-9ff0-34e783b786fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='testId-cc-login-form-email-input']</value>
      <webElementGuid>e45d12f7-ae47-42c4-a513-e3df9fdf015d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='testId-cc-login-form']/form/div/div/input</value>
      <webElementGuid>7dfdb81a-8620-4d0c-93b2-706b6c887fb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/input</value>
      <webElementGuid>5e368803-2323-4281-9aa4-e8455ab5c6bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'testId-cc-login-form-email-input' and @name = 'email' and @type = 'email' and @placeholder = 'Ingresa tu correo electrónico']</value>
      <webElementGuid>8677728c-da57-4301-943f-3cc020930345</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
