<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Departamento_geofinder-input-level1</name>
   <tag></tag>
   <elementGuidId>dec43f76-3e20-4741-aeac-6a8fa805b8bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='geofinder-input-level1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#geofinder-input-level1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Ingresa una departamento&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>187c58e6-4466-446c-aac5-26b5a3b5d933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Autocomplete-module_autocomplete-input__Mg01d</value>
      <webElementGuid>fb6e336a-4742-445e-888f-c59be6d8fd78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4ad333d1-0de6-4689-9f22-0b92442d2dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ingresa una departamento</value>
      <webElementGuid>461e66cd-bb22-4ae4-b004-0dfd7e70be29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a2524ec7-c6cf-4fdb-b731-28ac111de695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>33</value>
      <webElementGuid>b73f9c18-44c9-4e50-84ec-2c003aaf2456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>geofinder-input-level1</value>
      <webElementGuid>24b273f4-c63a-4c3d-b4f6-c9a211ea67be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;geofinder-input-level1&quot;)</value>
      <webElementGuid>f2aacf39-a265-4792-8654-86907ca94cfc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='geofinder-input-level1']</value>
      <webElementGuid>60d4c5b0-3126-4edd-aef6-f393a8edc4b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zone_modal_wrap']/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>0703e2c5-7c95-454f-ac02-f3921f25a0fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>7b4acccb-f861-4799-bb0d-cca90e2cbd5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Ingresa una departamento' and @id = 'geofinder-input-level1']</value>
      <webElementGuid>046ef23d-e004-43c9-846e-84b35f3b0c38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
