<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contrasea_testId-cc-login-form-passwo_119030</name>
   <tag></tag>
   <elementGuidId>1188c5f4-8dfb-4f08-abc5-9abf55702941</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='testId-cc-login-form-password-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#testId-cc-login-form-password-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Ingresa tu contraseña&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d4c79e46-89b0-4765-badf-06cd5116de83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>testId-cc-login-form-password-input</value>
      <webElementGuid>b55ea5f7-56db-44e2-bd1f-7f32f630174f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>551633da-d2d0-4bec-9667-85afbcc03bb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ingresa tu contraseña</value>
      <webElementGuid>04ef2e4d-63fd-4881-8438-cd3b841fcaf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>455abdd7-f81c-4e31-a21d-ca8b02921cb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-field-module_field-input__2sh6Y form-field-module_with-icon__4ht-m</value>
      <webElementGuid>02811b38-df46-4afd-b271-1b1b86495e3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;testId-cc-login-form-password-input&quot;)</value>
      <webElementGuid>b0c26d01-6679-402a-9430-4fbd90236a10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='testId-cc-login-form-password-input']</value>
      <webElementGuid>b09b5098-ddee-4cb6-9f22-d7d77e6d25d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='testId-cc-login-form']/form/div[2]/div/input</value>
      <webElementGuid>8104df7f-29b5-40f5-90a8-ddd6368c999d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>6efeb545-e247-48c7-834d-97e851dd4192</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'testId-cc-login-form-password-input' and @name = 'password' and @placeholder = 'Ingresa tu contraseña' and @type = 'password']</value>
      <webElementGuid>54dbd28a-1784-4ab9-8268-95de9ae7b48d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
