<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Correo electrnico_testId-cc-login-for_d0c7d1</name>
   <tag></tag>
   <elementGuidId>7d04e84e-e3d8-43f4-87f4-3382bccd7dcb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='testId-cc-login-form-email-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#testId-cc-login-form-email-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Ingresa tu correo electrónico&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aa8da6e7-4526-4c62-aade-6d84969bb0a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>testId-cc-login-form-email-input</value>
      <webElementGuid>e926fc23-ec35-4db8-8af3-8e0c890dfd31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>a1e91df6-168a-4ab1-90c8-7b340147fb05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>f79b9fdd-26f0-4763-96fd-f86b5075c8ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ingresa tu correo electrónico</value>
      <webElementGuid>4b02a1ab-ffb8-4099-8c07-db33ce11c227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-field-module_field-input__2sh6Y</value>
      <webElementGuid>7c837a45-acf6-4e44-86ae-0cb1dd07c0ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e7b76b76-4e5e-42b2-8bc5-365e3c638cc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;testId-cc-login-form-email-input&quot;)</value>
      <webElementGuid>e31534b1-056d-41ff-b45e-1347b956e2e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='testId-cc-login-form-email-input']</value>
      <webElementGuid>6935b908-6390-40f8-a40a-eaac076add41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='testId-cc-login-form']/form/div/div/input</value>
      <webElementGuid>1d56bfe1-8dde-4c3b-8404-db90b270178a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/input</value>
      <webElementGuid>9b3fd56b-40c0-4a00-ba3d-1645bddb25d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'testId-cc-login-form-email-input' and @name = 'email' and @type = 'email' and @placeholder = 'Ingresa tu correo electrónico']</value>
      <webElementGuid>502843f8-2dd3-44a5-b946-8baddece38d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
