<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Distrito_geofinder-input-level3</name>
   <tag></tag>
   <elementGuidId>fd819c46-ccab-4bbe-a5fd-af0701d3c761</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='geofinder-input-level3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#geofinder-input-level3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Ingresa un distrito&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5c5ad2ac-b521-465a-9e53-d0d0d165f844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Autocomplete-module_autocomplete-input__Mg01d</value>
      <webElementGuid>c5311a03-7206-4994-8eb1-41b86c29e174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6a6848b1-d368-4b42-bccf-467276b439ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ingresa un distrito</value>
      <webElementGuid>45614100-e67a-4e76-81d3-90baa216549c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d3b587d5-d01a-407b-a583-ac70e4319945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>33</value>
      <webElementGuid>0e437ae2-fd29-479b-ba5e-fb9168514323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>geofinder-input-level3</value>
      <webElementGuid>a260655c-6a1b-4328-aee5-e624c2377c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;geofinder-input-level3&quot;)</value>
      <webElementGuid>7fcb389f-b28b-49d2-a744-6694d4f7a9c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='geofinder-input-level3']</value>
      <webElementGuid>d1912c0f-8db4-4b48-8438-f912253f7b45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zone_modal_wrap']/div/div/div/div[2]/div[3]/div/div/input</value>
      <webElementGuid>278de876-ff0f-43fe-83a8-31f32e527894</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div/input</value>
      <webElementGuid>c5137c43-8a92-4e59-8fd2-cce99d7f39fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Ingresa un distrito' and @id = 'geofinder-input-level3']</value>
      <webElementGuid>5715dd47-95fd-4253-9cdd-d6a5d879211d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
