<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contrasea_testId-cc-login-form-passwo_119030</name>
   <tag></tag>
   <elementGuidId>1188c5f4-8dfb-4f08-abc5-9abf55702941</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='testId-cc-login-form-password-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#testId-cc-login-form-password-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Ingresa tu contraseña&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d5a88161-194d-4fa1-a7b6-03efc36a6c35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>testId-cc-login-form-password-input</value>
      <webElementGuid>3d405478-bb47-4205-ada0-5171d396d369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>29b75a0e-bf47-4ed3-b982-ad0925206967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ingresa tu contraseña</value>
      <webElementGuid>7caa4283-a97b-4647-977a-5f8ea722369d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>f8184217-4ac9-4a15-a230-a440d515d576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-field-module_field-input__2sh6Y form-field-module_with-icon__4ht-m</value>
      <webElementGuid>71d58ff2-3ef9-4501-ad9b-7489ce4e0243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;testId-cc-login-form-password-input&quot;)</value>
      <webElementGuid>c47fd94c-4fd9-4fbb-a4bd-9c4f637edbc3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='testId-cc-login-form-password-input']</value>
      <webElementGuid>2d4855c4-2751-4681-86e8-aabcbebdcbc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='testId-cc-login-form']/form/div[2]/div/input</value>
      <webElementGuid>8c3fbc72-3166-4342-a396-6cf6e2725a48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>d5b15424-22db-403f-a29c-020a3971d636</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'testId-cc-login-form-password-input' and @name = 'password' and @placeholder = 'Ingresa tu contraseña' and @type = 'password']</value>
      <webElementGuid>2b57cb90-6d72-402a-8f66-5637640ec931</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'testId-cc-login-form-password-input' and @name = 'password' and @placeholder = 'Ingresa tu contraseña' and @type = 'text']</value>
      <webElementGuid>23bf5472-ce08-429b-b272-c93bc11c650a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
