<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Men (2)</name>
   <tag></tag>
   <elementGuidId>627154fb-3017-4fc0-aef1-6fe75ca068ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='testId-HamburgerBtn-toggle']/div[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.MarketplaceHamburgerBtn-module_title__34MUP</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Menú&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3d2162ca-93e9-45b2-ac47-4b90eb073e9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MarketplaceHamburgerBtn-module_title__34MUP</value>
      <webElementGuid>48a58e0b-5ee1-458c-85a5-f8ab3df504b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Menú</value>
      <webElementGuid>db922d66-6330-4c13-abb9-1ff1b47b6951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;testId-HamburgerBtn-toggle&quot;)/div[@class=&quot;MediaComponent-module_tablet-desktop__9nJYW&quot;]/span[@class=&quot;MarketplaceHamburgerBtn-module_title__34MUP&quot;]</value>
      <webElementGuid>8c402483-67bd-40ae-a58d-e3572418bf12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='testId-HamburgerBtn-toggle']/div[2]/span</value>
      <webElementGuid>3654c771-883d-45d5-b371-fe54f351d834</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search Bar'])[1]/preceding::span[1]</value>
      <webElementGuid>6789b469-e44b-4471-966a-590f8f4175ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mis'])[1]/preceding::span[1]</value>
      <webElementGuid>91d08043-f51f-4880-97c8-6c41bdb14587</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Menú']/parent::*</value>
      <webElementGuid>16e87a6a-6764-4984-ac5c-ae96868e4c37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span</value>
      <webElementGuid>1b5c3f59-1259-42e5-a9c7-28f78a11741a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Menú' or . = 'Menú')]</value>
      <webElementGuid>c7550f33-a3ea-4d45-9502-a8b58d9fa9bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
