<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Men (9)</name>
   <tag></tag>
   <elementGuidId>cd1c6b68-1c67-4e31-9be9-224cdb4cf6f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='testId-HamburgerBtn-toggle']/div[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.MarketplaceHamburgerBtn-module_title__34MUP</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Menú&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c24d50ef-b46e-4e0e-862d-227687b77a4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MarketplaceHamburgerBtn-module_title__34MUP</value>
      <webElementGuid>b8677006-9d96-452c-be1a-527aaa82f37b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Menú</value>
      <webElementGuid>f9f76556-d8b6-47fe-83ce-3b70d57d1732</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;testId-HamburgerBtn-toggle&quot;)/div[@class=&quot;MediaComponent-module_tablet-desktop__9nJYW&quot;]/span[@class=&quot;MarketplaceHamburgerBtn-module_title__34MUP&quot;]</value>
      <webElementGuid>40fb6b1e-f8c3-41f0-9a4e-c962f562d1ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='testId-HamburgerBtn-toggle']/div[2]/span</value>
      <webElementGuid>a8203a7f-5def-4644-a120-fd6956b1e6dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search Bar'])[1]/preceding::span[1]</value>
      <webElementGuid>c94d649c-465f-470b-9963-41e60e700234</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mis'])[1]/preceding::span[1]</value>
      <webElementGuid>1758fde2-f9ce-49d5-bc82-15d99f6bf760</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Menú']/parent::*</value>
      <webElementGuid>757e0bdb-724a-4561-8442-3f5264722b53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span</value>
      <webElementGuid>e47ebb67-765a-4c18-a549-214c6fd63e01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Menú' or . = 'Menú')]</value>
      <webElementGuid>4bd73635-37fd-4863-9d68-efc91f7ef324</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
