<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Men_MarketplaceHamburgerBtn-module_lin_fa2b61</name>
   <tag></tag>
   <elementGuidId>da22e12c-f466-4096-b2d5-4dc4462a983b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='testId-HamburgerBtn-toggle']/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.MarketplaceHamburgerBtn-module_line__xQVGP</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Menú&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4a0eaaa1-4e54-4d3a-8747-13f9c411aebd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MarketplaceHamburgerBtn-module_line__xQVGP</value>
      <webElementGuid>0dc3d294-75cf-441b-b349-cc824b9a58fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;testId-HamburgerBtn-toggle&quot;)/div[@class=&quot;MarketplaceHamburgerBtn-module_icon__r2oRR&quot;]/div[@class=&quot;MarketplaceHamburgerBtn-module_icon-container__nCNAF&quot;]/span[@class=&quot;MarketplaceHamburgerBtn-module_line__xQVGP&quot;]</value>
      <webElementGuid>b0446b67-4753-48cd-818c-974338241c1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='testId-HamburgerBtn-toggle']/div/div/span</value>
      <webElementGuid>77bc5c08-c44a-40a6-8127-875e67fa9de7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>ee372210-2de6-4ebb-b192-50f8cb8416fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
