<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_compras</name>
   <tag></tag>
   <elementGuidId>16b78b13-dc49-4913-9dc3-3abc6ca00f41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='testId-userAction-orders']/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.UserActions-module_utils-span-lower__BiKMw</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Mis compras&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>71021be9-ff80-43ab-a6db-64e3d6f4338d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>UserActions-module_utils-span-lower__BiKMw</value>
      <webElementGuid>812bbfe3-da00-45c8-a454-d564e38153d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>compras</value>
      <webElementGuid>87a7c8f3-4860-4bdd-ba7e-bfc93f6dd248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;testId-userAction-orders&quot;)/span[@class=&quot;UserActions-module_utils-span-lower__BiKMw&quot;]</value>
      <webElementGuid>7c72c91a-62d1-4bea-9a15-2c9b579797e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='testId-userAction-orders']/span[2]</value>
      <webElementGuid>dd82c7cf-6fff-4bd5-aecf-66e32ab0b890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mis'])[1]/following::span[1]</value>
      <webElementGuid>dd31e4c3-51b5-4c31-a4d9-1a229732ec08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search Bar'])[1]/following::span[2]</value>
      <webElementGuid>1618d160-554c-49a6-b256-4c2e32bdbcf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='location-icon'])[1]/preceding::span[2]</value>
      <webElementGuid>be52de99-4a7c-4739-ac4b-75cbb025f714</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tarjeta CMR'])[1]/preceding::span[3]</value>
      <webElementGuid>75998608-2517-4ecf-86fb-c6de15ecf2a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='compras']/parent::*</value>
      <webElementGuid>1a66e85f-d5a0-42d7-a6c8-76cebee193b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>0b81d18e-db44-4e17-98c0-be6f02afdec1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'compras' or . = 'compras')]</value>
      <webElementGuid>68979760-d6b1-49c7-a880-ce18d82d2332</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
