<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Men_MarketplaceHamburgerBtn-module_lin_fa2b61</name>
   <tag></tag>
   <elementGuidId>e3b83529-c0a4-4e77-b59a-d390d0301c5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='testId-HamburgerBtn-toggle']/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.MarketplaceHamburgerBtn-module_line__xQVGP</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Menú&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7ba7c267-4db1-4342-83d0-578a627201f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MarketplaceHamburgerBtn-module_line__xQVGP</value>
      <webElementGuid>4829fbaf-c539-4481-9071-f995ef87f4c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;testId-HamburgerBtn-toggle&quot;)/div[@class=&quot;MarketplaceHamburgerBtn-module_icon__r2oRR&quot;]/div[@class=&quot;MarketplaceHamburgerBtn-module_icon-container__nCNAF&quot;]/span[@class=&quot;MarketplaceHamburgerBtn-module_line__xQVGP&quot;]</value>
      <webElementGuid>d219a06e-650d-4346-b0d8-d3b71bf15531</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='testId-HamburgerBtn-toggle']/div/div/span</value>
      <webElementGuid>33104afe-4364-4661-8803-a2584e95beef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>06311f57-948f-46d2-839a-eda10e0841c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
