<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Men_MarketplaceHamburgerBtn-module_lin_fa2b61</name>
   <tag></tag>
   <elementGuidId>7ed2e14d-b6e5-4656-b7b2-36fb37feccfb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.MarketplaceHamburgerBtn-module_line__xQVGP</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='testId-HamburgerBtn-toggle']/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Menú&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cd56735f-4088-40a9-b6f4-23bc15e42d00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MarketplaceHamburgerBtn-module_line__xQVGP</value>
      <webElementGuid>a0191b9a-57f2-42ed-8120-c9afe38b50b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;testId-HamburgerBtn-toggle&quot;)/div[@class=&quot;MarketplaceHamburgerBtn-module_icon__r2oRR&quot;]/div[@class=&quot;MarketplaceHamburgerBtn-module_icon-container__nCNAF&quot;]/span[@class=&quot;MarketplaceHamburgerBtn-module_line__xQVGP&quot;]</value>
      <webElementGuid>0c9a5925-17b5-4087-a3eb-c56a5b6e4e57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='testId-HamburgerBtn-toggle']/div/div/span</value>
      <webElementGuid>0ee714f3-2ffe-4d7d-8460-da2e94700727</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>c55a599d-8ca5-4daa-bb08-637c54c1190c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
