<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Ir al Carro</name>
   <tag></tag>
   <elementGuidId>a4bbf88a-8309-459b-8761-186ac0dc2037</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#linkButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='linkButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Ir al Carro&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0f57aa80-b579-493a-ab1b-ff173d71eff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>linkButton</value>
      <webElementGuid>f2c7759d-14b5-4552-a04d-faeb17b71035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.falabella.com.pe/falabella-pe/basket</value>
      <webElementGuid>e4595e9f-8781-4b11-8c73-ff91f894fc1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jsx-2760526313 button button-mkp-secondary button-medium</value>
      <webElementGuid>c5944e45-1d43-4a1d-ab9d-f6ac1c446e0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ir al Carro</value>
      <webElementGuid>64595c16-3561-4a12-a33c-3f42fd228a7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;linkButton&quot;)</value>
      <webElementGuid>3fa86863-2be0-4b49-82f0-da8f140e93c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='linkButton']</value>
      <webElementGuid>2babd3f5-4c6a-4127-98e2-2005c612e18c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Ir al Carro')])[2]</value>
      <webElementGuid>e968a6ed-9f0c-4f9d-b1b8-4f35df95adf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seguir comprando'])[2]/following::a[1]</value>
      <webElementGuid>4e0d0cd4-c202-4060-be69-98f6c060cb82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Los productos de tu carro de compras pueden agotarse próximamente. Cómpralos pronto.'])[1]/following::a[1]</value>
      <webElementGuid>d98f01a2-776b-4bd9-b2fc-c597e01c06be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://www.falabella.com.pe/falabella-pe/basket')])[3]</value>
      <webElementGuid>62b46336-49b1-425b-87d4-454818bba33a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/div/div[3]/div[2]/div/a</value>
      <webElementGuid>2092eddd-4d04-44b3-8ad7-70a13cfd2f97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'linkButton' and @href = 'https://www.falabella.com.pe/falabella-pe/basket' and (text() = 'Ir al Carro' or . = 'Ir al Carro')]</value>
      <webElementGuid>4005bed0-19df-4864-90da-d81e027d8c8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
