<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Aceptar_testId-close-cookies-btn</name>
   <tag></tag>
   <elementGuidId>4cd3dcf3-3010-44e3-a209-eac72013f143</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#testId-close-cookies-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='testId-close-cookies-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#testId-close-cookies-btn</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>348eed82-71d3-4a29-87aa-947b268db45b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>testId-close-cookies-btn</value>
      <webElementGuid>e1da1d5d-3a14-4a53-a070-ac440e3005fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Footer-module_close-legal-banner__Tuqyl</value>
      <webElementGuid>7d4b4d39-a119-46d5-bc10-4bc580848251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;testId-close-cookies-btn&quot;)</value>
      <webElementGuid>0d510aa7-f267-475b-b225-a6cfce599148</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='testId-close-cookies-btn']</value>
      <webElementGuid>69c22a9d-1803-4152-bb77-d8fa3756af94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/footer/section[4]/div</value>
      <webElementGuid>5b01d34a-4095-450a-a47a-d7a8308fbc16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[4]/div</value>
      <webElementGuid>76cb4c82-33c6-439b-9ba8-61e1dc43dada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'testId-close-cookies-btn']</value>
      <webElementGuid>76e738ae-d2e5-4350-86c7-fc46a8732228</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
