<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Agregar al Carro_testId-pod-image-https_b99a14</name>
   <tag></tag>
   <elementGuidId>69270770-4d6f-416b-80a9-05366fa83f2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//img[@id='testId-pod-image-https://media.falabella.com.pe/falabellaPE/20933319_1/public'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;SAMSUNG - Galaxy A56 5g 256gb Black SAMSUNG Galaxy A56 5g 256gb Black Por Falabella S/ 1,199 -37% S/ 1,399 S/ 1,899 Llega mañana Retira hoy Envío en 180 minutos      (420) Agregar al Carro&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ad74fdfc-a0b6-438b-966e-8a4e10cf06da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://media.falabella.com.pe/falabellaPE/20933319_1/width=240,height=240,quality=70,format=webp,fit=pad</value>
      <webElementGuid>58e5839d-31a5-4482-bad8-3eaee6b38480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://media.falabella.com.pe/falabellaPE/20933319_1/width=480,height=480,quality=70,format=webp,fit=pad 2x</value>
      <webElementGuid>fd7f0726-4dbe-4156-aa97-9378ab10316b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>SAMSUNG - Galaxy A56 5g 256gb Black</value>
      <webElementGuid>289d88e4-200d-4233-bfa0-eb931450c860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>testId-pod-image-https://media.falabella.com.pe/falabellaPE/20933319_1/public</value>
      <webElementGuid>3cbc5c40-25e2-4834-a234-e0d41aaad667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>240</value>
      <webElementGuid>e7e80244-43e8-4888-acba-f099de78f961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>240</value>
      <webElementGuid>a326695b-b89e-4b52-b18d-c813fe2bb5d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jsx-1996933093</value>
      <webElementGuid>5eb60be2-43ef-4fe1-8457-adf3d342de26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;testId-pod-20933319&quot;)/div[@class=&quot;jsx-4134261027 jsx-3390574944 pod-head&quot;]/div[@class=&quot;jsx-1273315118&quot;]/section[@class=&quot;jsx-1273315118 image--active layout_grid-view layout_view_4_GRID&quot;]/picture[@class=&quot;jsx-1996933093&quot;]/img[@id=&quot;testId-pod-image-https://media.falabella.com.pe/falabellaPE/20933319_1/public&quot;]</value>
      <webElementGuid>b60b7ec6-9388-4b4b-bb90-b9a65f35301b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//img[@id='testId-pod-image-https://media.falabella.com.pe/falabellaPE/20933319_1/public'])[2]</value>
      <webElementGuid>eb7db4ba-f596-4270-aa90-f8f288def1a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='testId-pod-20933319']/div/div/section/picture/img</value>
      <webElementGuid>71c5a2e5-85d2-409c-8370-02baf7be2f56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='SAMSUNG - Galaxy A56 5g 256gb Black'])[6]</value>
      <webElementGuid>a734be6d-c1c3-47fe-97f1-9f17c0cf540b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/div/div/section/picture/img</value>
      <webElementGuid>60452aae-2f26-421f-933c-640cbd284747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://media.falabella.com.pe/falabellaPE/20933319_1/width=240,height=240,quality=70,format=webp,fit=pad' and @alt = 'SAMSUNG - Galaxy A56 5g 256gb Black' and @id = 'testId-pod-image-https://media.falabella.com.pe/falabellaPE/20933319_1/public']</value>
      <webElementGuid>2274f8d3-cf1c-41af-a313-47c36ae610ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
