<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__testId-pod-image-httpsmedia.falabella._48c18b</name>
   <tag></tag>
   <elementGuidId>fb1dc1a7-af42-4ca3-ab29-502c9c0a26d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//img[@id='testId-pod-image-https://media.falabella.com.pe/falabellaPE/18673460_1/public'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;APPLE - IPhone 13 128GB APPLE IPhone 13 128GB Por Falabella S/ 1,899 -57% S/ 1,999 S/ 4,399 Llega mañana Retira hoy 18Cuotas Sin Interes CMR      (1788) Agregar al Carro&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e0390f2b-3762-4a18-b217-e548dbea24f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://media.falabella.com.pe/falabellaPE/18673460_1/width=240,height=240,quality=70,format=webp,fit=pad</value>
      <webElementGuid>adb841e9-242d-4ffb-91e0-ead81f29a8ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://media.falabella.com.pe/falabellaPE/18673460_1/width=480,height=480,quality=70,format=webp,fit=pad 2x</value>
      <webElementGuid>4163a5a2-95e6-4956-8ae6-5808bc00191a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>APPLE - IPhone 13 128GB</value>
      <webElementGuid>522e5dd3-4d60-4cd3-8764-38d875396c38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>testId-pod-image-https://media.falabella.com.pe/falabellaPE/18673460_1/public</value>
      <webElementGuid>84da9bf1-7d9f-48e0-92f8-7066693cf726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>240</value>
      <webElementGuid>7dd42431-8946-4bb3-a7e6-f897cdd9d662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>240</value>
      <webElementGuid>f8d6d047-1487-4ad5-bac2-8bab226a35d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fetchpriority</name>
      <type>Main</type>
      <value>high</value>
      <webElementGuid>7b268788-34c6-4802-ab1c-57c7e5bf45a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jsx-1996933093</value>
      <webElementGuid>5df75390-d93b-4ea8-9cf9-858bcf9780e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;testId-pod-18673460&quot;)/div[@class=&quot;jsx-4134261027 jsx-3390574944 pod-head&quot;]/div[@class=&quot;jsx-1273315118&quot;]/section[@class=&quot;jsx-1273315118 image--active layout_grid-view layout_view_4_GRID&quot;]/picture[@class=&quot;jsx-1996933093&quot;]/img[@id=&quot;testId-pod-image-https://media.falabella.com.pe/falabellaPE/18673460_1/public&quot;]</value>
      <webElementGuid>60b6b535-521b-4dac-ab91-79b7e2d5d564</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//img[@id='testId-pod-image-https://media.falabella.com.pe/falabellaPE/18673460_1/public'])[2]</value>
      <webElementGuid>d970dbbf-4cd5-4922-9367-1483529a922f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='testId-pod-18673460']/div/div/section/picture/img</value>
      <webElementGuid>9afc51f7-50a9-418e-98cf-d2d7cad2ade7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='APPLE - IPhone 13 128GB'])[6]</value>
      <webElementGuid>afe631a3-665d-4348-82f1-1d56488c2218</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/picture/img</value>
      <webElementGuid>08450437-ad53-444b-9e1c-f13581dc0f63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://media.falabella.com.pe/falabellaPE/18673460_1/width=240,height=240,quality=70,format=webp,fit=pad' and @alt = 'APPLE - IPhone 13 128GB' and @id = 'testId-pod-image-https://media.falabella.com.pe/falabellaPE/18673460_1/public']</value>
      <webElementGuid>8bd9e34d-0b53-4f56-89e6-23fcebb05ff2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
